version: '3.8'

services:
  nginx:
    image: nginx:jungmiho
    build: 
      context: ./requirements/nginx
    environment:
      CERTS_: ${CERTS_}
    ports:
      - "443:443"
    volumes:
      - web-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - webnet

  wordpress:
    image: wordpress:jungmiho
    build: 
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: "${WP_TITLE}"
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_EMAIL: ${WP_EMAIL}
    volumes:
      - web-data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - webnet

  mariadb:
    image: mariadb:jungmiho
    build: 
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jungmiho/data/mariadb
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jungmiho/data/wordpress

networks:
  webnet:
