# latest Debian image: bookworm, second latest: bullseye
FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y mariadb-server && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./tools/50-server.cnf /etc/mysql/mariadb.conf.d/

COPY ./tools/script.sh /script.sh

RUN chmod +x /script.sh

# when a container is started from this image, the script will be executed
CMD ["/script.sh"]
