# latest Debian image: bookworm, second latest: bullseye
FROM debian:bullseye

# -php-fpm: handle PHP requests
# -php-mysql: connect to MySQL databases
# -curl: download files from the internet
# -default-mysql-client: connect to MySQL databases
RUN apt update -y && \
    apt install -y \
    php-fpm \
    php-mysql \
    curl \
    default-mysql-client

# Copy the WordPress files into the container
# script.sh: initialize the WordPress installation
# wp-config.php: WordPress configuration file
COPY ./tools/script.sh /
COPY ./tools/wp-config.php /

RUN chmod +x /script.sh

CMD ["/script.sh"]
